#!/bin/sh

# Navigation
alias \
    ..="cd .." \
    ...="cd ../.." \
    .3="cd ../../.." \
    .4="cd ../../../.." \
    .5="cd ../../../../.." \
    .ls="cd ~/.local/share" \
    config="cd ~/.config/" \
    dl="cd ~/extra/dl" \
    docs="cd ~/extra/docs" \
    vids="cd ~/extra/vids" \
    music="cd ~/extra/music" \
    pics="cd ~/extra/pics" \
    movies="vids; cd movies" \
    tv="vids; cd tv" \
    meme="vids; cd memes" \
    pr="cd ~/proj/" \
    downgrade="vim ~/.local/downgrade" \
    tree="exa --tree" \
    bk="cd ~/extra/docs/books" \
    ls="ls --color=auto" \
    ldwm="cd ~/.local/src/dwm" \
    lsdwm="cd ~/.local/share/dwm; vim autostart.sh" \
    bin="cd ~/.local/bin" \
    sb="cd ~/.local/bin/statusbar" \
    bkup="cd ~/projects/github/artix/" \
    lb="cd ~/.local/bin" \
    nf="fastfetch" \
    bashrc="vim ~/.bashrc" \
    rl="vim ~/extra/docs/runlogs/may.11.2025"\ 

# Too long 
alias \
    sdn="sudo shutdown -h now" \
    v="vim ." \
    vi="vim" \
    nv="nvim" \
    Hyprland="dbus-run-session Hyprland" \
    vk="hyprctl plugin load ~/.local/share/hyprpm/csgo-vulkan-fix.so" \
    ns="cd ~/extra/docs/Obsidian/" \
    hcs2="hyprpm enable csgo-vulkan-fix" \

# Quality of life
alias \
    yta="music; yt-dlp --embed-metadata -xic -f bestaudio/best --restrict-filenames" \
    yts="music; yt-dlp --embed-metadata -xic --audio-format mp3 --audio-quality 0 --restrict-filenames" \
    ytm="meme; yt-dlp --restrict-filenames" \
    ytf="vids; yt-dlp -f bestvideo+bestaudio" \
    cp="cp -i" \
    mv="mv -i" \
    rm="rm -i" \
    notes="cd ~/extra/docs/Obsidian && notes" \

# system
alias \
    p="pacman" \
    sp="sudo pacman" \
    sps="sudo pacman -S" \
    pug="sudo pacman -Syu; pkill -RTMIN+8 waybar" \
    sdn="loginctl poweroff" \

# git
alias \
    g="git" \
    gs="git status" \
    ga="git add" \
    gc="git commit -m" \
    gp="git push" \
    gpf="git push --force" \
    gpl="git pull" \
    gplr="git pull --recurse-submodules" \
    grb="git rebase" \

# Programming
alias \
    cr="cargo run" \
    cn="cargo new" \
    cb="cargo build" \
    aliasrc="vim ~/.config/shell/aliasrc" \
    zshrc="vim ~/.config/zsh/.zshrc" \
    t="tmux" \
    ts="tmux && tmux-sessionizer"\
    ta="tmux a -t"\
    tks="tmux kill-session -a -t"\
    tns="tmux new -s"\
    hss="hugo server --noHTTPCache"\
