"$schema" = "https://yazi-rs.github.io/schemas/keymap.json"

[mgr]
prepend_keymap = [
  { on = ".", run = "hidden", desc = "Toggle hidden files" },

  { on = "D", run = "remove --permanently", desc = "Delete permanently" },

  { on = "p", run = "paste", desc = "Paste" },
  { on = "x", run = "yank --cut", desc = "Cut" },
  { on = "y", run = "yank", desc = "Copy" },

  { on = "<Enter>", run = "open", desc = "Open" },

  { on = "R", run = "reload", desc = "Reload" },

  { on = "C", run = "clear", desc = "Clear selection/tasks" },

  { on = "v", run = "open_with mpv", desc = "Open with mpv (playlist for multiples)" },
  { on = "c", run = "open_with nvim", desc = "Edit with nvim" },

  { on = ["g", "d"], run = "cd ~/extra/dl", desc = "Go to downloads" },
  { on = ["g", "D"], run = "cd ~/extra/docs/", desc = "Go to docs" },
  { on = ["g", "p"], run = "cd ~/extra/pics", desc = "Go to pics" },
  { on = ["g", "P"], run = "cd ~/projects/", desc = "Go to projects" },
  { on = ["g", "c"], run = "cd ~/.config", desc = "Go to config" },
  { on = ["g", "v"], run = "cd ~/extra/vids", desc = "Go to videos" },
  { on = ["g", "b"], run = "cd ~/extra/docs/books", desc = "Go to books" },
  { on = ["g", "B"], run = "cd ~/.local/bin", desc = "Go to bin" },
  { on = ["g", "o"], run = "cd ~/extra/docs/Obsidian", desc = "Go to Obsidian" },

  { on = ["g", "a"], run = "cd /mnt/anime", desc = "Go to anime" },
  { on = ["g", "t"], run = "cd /mnt/tv", desc = "Go to tv" },
  { on = ["g", "m"], run = "cd /mnt/movies", desc = "Go to movies" },
  { on = ["g", "M"], run = "cd /mnt", desc = "Go to mnt root" },
  { on = ["g", "e"], run = "cd /mnt/pics", desc = "Go to mnt pics" },
  { on = ["g", "l"], run = "cd /mnt/docs", desc = "Go to mnt docs" },
  { on = ["g", "r"], run = "cd /mnt/m2/clips", desc = "Go to m2 clips" },

]
